name: Dev Task
description: Use this template to create a new development task.
title: "[Dev Task]:"
labels: ["dev", "task"]
body:
  - type: markdown
    attributes:
      value: "### 🚀 Development Task Overview\nProvide a brief summary of the development task."
      
  - type: textarea
    id: background-information
    attributes:
      label: "📚 Background Information"
      description: "Provide context and necessary details about the project or issue, including relevant history or previous decisions."
      placeholder: "Describe background information..."
    validations:
      required: true
      
  - type: textarea
    id: improvements
    attributes:
      label: "💡 Improvements"
      description: "Outline the specific changes or enhancements to be made, including how they add value or address current challenges."
      placeholder: "List the improvements..."
    validations:
      required: true

  - type: textarea
    id: other-suggestions
    attributes:
      label: "📝 Other Suggestions"
      description: "Include any additional ideas, alternative approaches, or recommendations that could further optimize the outcome."
      placeholder: "Any other suggestions..."

