//Verilog generated by VPR 9.0.0-dev+v8.0.0-11943-g8cb20aa52-dirty from post-place-and-route implementation
module LUT (
    input \I1 ,
    input \I2 ,
    input \I3 ,
    input \I4 ,
    output \O1 
);

    //Wires
    wire \I1_output_0_0 ;
    wire \I2_output_0_0 ;
    wire \I3_output_0_0 ;
    wire \I4_output_0_0 ;
    wire \lut_O1_output_0_0 ;
    wire \lut_O1_input_0_4 ;
    wire \lut_O1_input_0_2 ;
    wire \lut_O1_input_0_0 ;
    wire \lut_O1_input_0_1 ;
    wire \O1_input_0_0 ;

    //IO assignments
    assign \O1  = \O1_input_0_0 ;
    assign \I1_output_0_0  = \I1 ;
    assign \I2_output_0_0  = \I2 ;
    assign \I3_output_0_0  = \I3 ;
    assign \I4_output_0_0  = \I4 ;

    //Interconnect
    fpga_interconnect \routing_segment_I1_output_0_0_to_lut_O1_input_0_4  (
        .datain(\I1_output_0_0 ),
        .dataout(\lut_O1_input_0_4 )
    );

    fpga_interconnect \routing_segment_I2_output_0_0_to_lut_O1_input_0_2  (
        .datain(\I2_output_0_0 ),
        .dataout(\lut_O1_input_0_2 )
    );

    fpga_interconnect \routing_segment_I3_output_0_0_to_lut_O1_input_0_0  (
        .datain(\I3_output_0_0 ),
        .dataout(\lut_O1_input_0_0 )
    );

    fpga_interconnect \routing_segment_I4_output_0_0_to_lut_O1_input_0_1  (
        .datain(\I4_output_0_0 ),
        .dataout(\lut_O1_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_O1_output_0_0_to_O1_input_0_0  (
        .datain(\lut_O1_output_0_0 ),
        .dataout(\O1_input_0_0 )
    );


    //Cell instances
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000100000000000000000000000)
    ) \lut_O1  (
        .in({
            \lut_O1_input_0_4 ,
            1'b0,
            \lut_O1_input_0_2 ,
            \lut_O1_input_0_1 ,
            \lut_O1_input_0_0 
         }),
        .out(\lut_O1_output_0_0 )
    );


endmodule
